# Ejercicio 3

En este ejercicio se aplicará una mascara de interés a una imagen.

In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def mascara(img, mask):
    return img*mask

In [3]:
ejemplo = np.array([
    [1,1,1,3],
    [2,1,1,1],
    [3,2,1,1],
    [1,1,1,2]
])
mask = np.array([
    [1,0,1,1],
    [1,0,1,1],
    [1,0,1,0],
    [1,0,1,0]
])

print(mascara(ejemplo, mask))

[[1 0 1 3]
 [2 0 1 1]
 [3 0 1 0]
 [1 0 1 0]]
