# Ejercicio 1

En este ejercicio definiremos una función que sea capaz de aplicar un filtrado lineal a una imagen monobanda con diferentes matrices de filtrado de 3x3.

In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

imagen = cv.imread('imgpack/Monobanda/2_Corsica.jpg',cv.IMREAD_GRAYSCALE)

Para ellos usaremos una función que sea capaz de aplicar el filtro a cada pixel acudiendo a los valores de los 8 pixeles vecinos, y sustituyendo el valor del pixel consultado por la influencia que producen los vecinos.

In [2]:
# En esta función auxiliar realizaremos la parte aritmética del cálculo del nuevo valor del pixel.
def aux(img,a,b,cf,fc,cc,offsetF,offsetC):
    
    p=0
    
    # Este bucle realizara la busqueda de los valores de los pixeles vecinos al pixel consultado
    # para posteriormente realizar el cálculo requerido para la modificación de su valor.
    for i in range(-offsetF,offsetF+1):
        for j in range(-offsetC,offsetC+1):
            p += img[a+i][b+j]*cf[fc+i][cc+j]
            
    return p

In [3]:
def filtro(img, cf):
    
    # Para empezar realizaremos una copia de la imagen para no modificar la imagen original.
    resimg = img.copy()
    
    # Teniendo en cuenta que estaremos usando matrices de 3x3 no necesitariamos acudir a funciones
    # especificas para calcular cuantas filas y columnas se dejaran a 0, sin embargo supondremos que
    # a nuestro codigo le podremos meter cualquier matriz cuadrática.
    ceros = int(len(cf)/2)
    
    # Este bucle es el encargado de valorar a 0 los pixeles de las filas y columnas borde.
    for i in range(len(resimg)):
        if(i<ceros):
            resimg[i] = 0
            resimg[-(i+1)] = 0
        for j in range(ceros):
            resimg[i][j] = 0
            resimg[i][-(j+1)] = 0
    
    # Al igual que se ha comentado anteriormente, supondremos que fc y cc se calcularan de forma
    # correspondiente a la matriz entrante y no simplemente aplicando el conocimiento previo de
    # que la matriz es 3x3 y se cumpliria fc = cc = 1.
    fc = int(len(cf)/2)
    cc = int(len(cf[0])/2)
    
    # Realizamos el mismo procedimiento anterior para asignar los valores de offsetF y offsetC.
    offsetF = int(len(cf)/2)
    offsetC = int(len(cf[0])/2)
    
    # A continuación realizaremos el bucle para modificar el valor de los pixeles finales.
    for i in range(len(resimg)):
        for j in range(len(resimg[i])):
            # Con esta secuencia de condicionales nos aseguraremos de no acudir a ningún pixel
            # con valor 0.
            if(not(i==0 or j == 0 or i == len(resimg)-1 or j == len(resimg[i])-1)):
                # Para no empeorar la vision del código la función aux sera definida más arriba.
                resimg[i][j] = np.round(aux(img,i,j,cf,fc,cc,offsetF,offsetC)/np.sum(cf))
    
    return resimg

In [4]:
cf = np.array([[1,1,1],[1,2,1],[1,1,1]])
print(cf)

[[1 1 1]
 [1 2 1]
 [1 1 1]]


In [5]:
ejemplo = np.array([[12,14,17,24,32,30],
                    [19,18,17,26,36,40],
                    [26,21,17,28,40,42],
                    [20,19,18,26,33,35],
                    [14,17,20,23,27,20],
                    [35,14,22,13,40,21]])
print(ejemplo)

[[12 14 17 24 32 30]
 [19 18 17 26 36 40]
 [26 21 17 28 40 42]
 [20 19 18 26 33 35]
 [14 17 20 23 27 20]
 [35 14 22 13 40 21]]


In [6]:
print(filtro(ejemplo,cf))

[[ 0  0  0  0  0  0]
 [ 0 18 20 26 33  0]
 [ 0 20 21 27 35  0]
 [ 0 19 21 26 31  0]
 [ 0 20 19 24 26  0]
 [ 0  0  0  0  0  0]]
